CREATE TABLE IF NOT EXISTS "gamification_invitation_code" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "code" varchar(8) NOT NULL,
    "status" tinyint NOT NULL,
    "total_invitations" int NOT NULL DEFAULT 0,
    "valid_invitations" int NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "gamification_invitation_relation" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "inviter_id" bigint NOT NULL,
    "invitee_id" bigint NOT NULL,
    "invitation_code" varchar(8) NOT NULL,
    "status" tinyint NOT NULL,
    "register_time" timestamp NOT NULL,
    "complete_time" timestamp DEFAULT NULL,
    "device_fingerprint" varchar(64) DEFAULT NULL,
    "register_ip" varchar(64) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "gamification_invitation_reward" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "relation_id" bigint NOT NULL,
    "inviter_id" bigint NOT NULL,
    "invitee_id" bigint NOT NULL,
    "reward_type" varchar(32) NOT NULL,
    "reward_points" int NOT NULL,
    "status" tinyint NOT NULL,
    "grant_time" timestamp DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "gamification_invitation_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "config_key" varchar(64) NOT NULL,
    "config_value" varchar(255) NOT NULL,
    "description" varchar(255) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
