-- 五金商城三泳道动态分类与搜索即溯源模块建表语句

CREATE TABLE IF NOT EXISTS `wujin_category` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '分类编号',
    `parent_id` bigint NOT NULL COMMENT '父分类编号，根节点为 0',
    `lane` varchar(32) NOT NULL COMMENT '泳道：PRODUCT/PROCESS/MATERIAL',
    `code` varchar(64) NOT NULL COMMENT '分类编码',
    `name` varchar(128) NOT NULL COMMENT '分类名称',
    `level` int NOT NULL COMMENT '分类层级',
    `sort` int DEFAULT 0 COMMENT '排序',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `display_depth` int DEFAULT NULL COMMENT '默认展示深度',
    `health_status` varchar(32) DEFAULT NULL COMMENT '健康状态',
    `description` varchar(512) DEFAULT NULL COMMENT '分类说明',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_wujin_category_code` (`code`, `deleted`),
    KEY `idx_wujin_category_parent` (`parent_id`),
    KEY `idx_wujin_category_lane` (`lane`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金三泳道分类';

CREATE TABLE IF NOT EXISTS `wujin_category_mapping` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '映射编号',
    `source_category_id` bigint NOT NULL COMMENT '来源分类编号',
    `source_lane` varchar(32) NOT NULL COMMENT '来源泳道',
    `target_category_id` bigint NOT NULL COMMENT '目标分类编号',
    `target_lane` varchar(32) NOT NULL COMMENT '目标泳道',
    `mapping_type` varchar(64) NOT NULL COMMENT '映射类型',
    `confidence` int DEFAULT NULL COMMENT '置信度',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `risk_note` varchar(512) DEFAULT NULL COMMENT '风险说明',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_mapping_source` (`source_category_id`, `source_lane`),
    KEY `idx_wujin_mapping_target` (`target_category_id`, `target_lane`),
    KEY `idx_wujin_mapping_type` (`mapping_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金跨泳道分类映射';

CREATE TABLE IF NOT EXISTS `wujin_chain_entity` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '实体编号',
    `entity_code` varchar(64) NOT NULL COMMENT '实体编码',
    `name` varchar(128) NOT NULL COMMENT '实体名称',
    `lane` varchar(32) NOT NULL COMMENT '语义泳道：PRODUCT/PROCESS/MATERIAL',
    `industries` varchar(512) DEFAULT NULL COMMENT '适用行业，逗号分隔',
    `junction_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否交汇点实体',
    `risk_note` varchar(512) DEFAULT NULL COMMENT '风险说明',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_wujin_chain_entity_code` (`entity_code`, `deleted`),
    KEY `idx_wujin_chain_entity_lane` (`lane`),
    KEY `idx_wujin_chain_entity_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金产业链实体';

CREATE TABLE IF NOT EXISTS `wujin_chain_entity_relation` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '关系编号',
    `source_entity_id` bigint NOT NULL COMMENT '下游实体编号',
    `target_entity_id` bigint NOT NULL COMMENT '上游实体编号',
    `relation_type` varchar(64) NOT NULL COMMENT '关系类型',
    `weight` int DEFAULT NULL COMMENT '权重，百分制',
    `cost_ratio` int DEFAULT NULL COMMENT '成本占比，百分制',
    `industry_context` varchar(64) DEFAULT NULL COMMENT '适用行业上下文',
    `audit_status` tinyint NOT NULL COMMENT '审核状态：0=待审 1=通过 2=驳回',
    `audit_remark` varchar(512) DEFAULT NULL COMMENT '审核备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_chain_relation_source` (`source_entity_id`),
    KEY `idx_wujin_chain_relation_target` (`target_entity_id`),
    KEY `idx_wujin_chain_relation_type` (`relation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金产业链实体上下游关系';

CREATE TABLE IF NOT EXISTS `wujin_industry_template` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板编号',
    `template_code` varchar(64) NOT NULL COMMENT '模板编码',
    `name` varchar(128) NOT NULL COMMENT '模板名称',
    `industry_code` varchar(64) NOT NULL COMMENT '行业编码',
    `product_lane` varchar(32) NOT NULL COMMENT '成品泳道：PRODUCT',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_wujin_industry_template_code` (`template_code`, `deleted`),
    KEY `idx_wujin_industry_template_industry` (`industry_code`),
    KEY `idx_wujin_industry_template_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金行业模板';

CREATE TABLE IF NOT EXISTS `wujin_industry_template_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '模板项编号',
    `template_id` bigint NOT NULL COMMENT '模板编号',
    `entity_id` bigint NOT NULL COMMENT '关联实体编号',
    `relation_type` varchar(64) NOT NULL COMMENT '关系类型',
    `required_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必填',
    `sort` int DEFAULT 0 COMMENT '排序',
    `weight` int DEFAULT NULL COMMENT '权重，百分制',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_template_item_template` (`template_id`),
    KEY `idx_wujin_template_item_entity` (`entity_id`),
    KEY `idx_wujin_template_item_relation` (`relation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金行业模板项';

CREATE TABLE IF NOT EXISTS `wujin_merchant_relation_submission` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '申报编号',
    `merchant_id` bigint NOT NULL COMMENT '商家编号',
    `product_id` bigint NOT NULL COMMENT '商品编号',
    `product_name` varchar(128) NOT NULL COMMENT '商品名称',
    `product_lane` varchar(32) NOT NULL COMMENT '商品泳道：PRODUCT',
    `product_category_id` bigint DEFAULT NULL COMMENT '商品分类编号',
    `template_id` bigint NOT NULL COMMENT '行业模板编号',
    `audit_status` tinyint NOT NULL COMMENT '审核状态：0=待审 1=通过 2=驳回',
    `audit_route` varchar(64) DEFAULT NULL COMMENT '审核路线：AUTO_APPROVE/MANUAL_REVIEW',
    `completeness_score` int DEFAULT NULL COMMENT '完善度分数',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_merchant_submission_merchant` (`merchant_id`),
    KEY `idx_wujin_merchant_submission_product` (`product_id`),
    KEY `idx_wujin_merchant_submission_audit` (`audit_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金商家关系申报';

CREATE TABLE IF NOT EXISTS `wujin_merchant_relation_item` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '申报项编号',
    `submission_id` bigint NOT NULL COMMENT '申报编号',
    `entity_id` bigint NOT NULL COMMENT '关联实体编号',
    `relation_type` varchar(64) NOT NULL COMMENT '关系类型',
    `from_template` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否来自模板',
    `required_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必填',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_relation_item_submission` (`submission_id`),
    KEY `idx_wujin_relation_item_entity` (`entity_id`),
    KEY `idx_wujin_relation_item_type` (`relation_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金商家关系申报项';

CREATE TABLE IF NOT EXISTS `wujin_merchant_supply_capability` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '供应能力编号',
    `merchant_id` bigint NOT NULL COMMENT '商家编号',
    `product_id` bigint NOT NULL COMMENT '商品编号',
    `product_name` varchar(128) NOT NULL COMMENT '商品名称',
    `entity_id` bigint NOT NULL COMMENT '关联产业链实体编号',
    `lane` varchar(32) NOT NULL COMMENT '供应泳道：PRODUCT/PROCESS/MATERIAL',
    `industry` varchar(64) DEFAULT NULL COMMENT '行业上下文',
    `supply_status` tinyint NOT NULL COMMENT '供应状态：0=启用 1=停供',
    `stock_count` int DEFAULT NULL COMMENT '库存数量',
    `min_order_quantity` int DEFAULT NULL COMMENT '最小起订量',
    `delivery_days` int DEFAULT NULL COMMENT '交付周期天数',
    `service_area` varchar(128) DEFAULT NULL COMMENT '服务区域',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_supply_capability_merchant` (`merchant_id`),
    KEY `idx_wujin_supply_capability_product` (`product_id`),
    KEY `idx_wujin_supply_capability_entity` (`entity_id`),
    KEY `idx_wujin_supply_capability_lane` (`lane`, `industry`),
    KEY `idx_wujin_supply_capability_status` (`supply_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金商家供应能力索引';

CREATE TABLE IF NOT EXISTS `wujin_relation_audit_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '审核记录编号',
    `submission_id` bigint NOT NULL COMMENT '申报编号',
    `auditor_id` bigint NOT NULL COMMENT '审核人编号',
    `action` varchar(64) NOT NULL COMMENT '审核动作：BLOCK/SUGGEST_MERGE/MANUAL_REVIEW/APPROVE/REJECT',
    `reason` varchar(64) NOT NULL COMMENT '审核原因',
    `comment` varchar(512) DEFAULT NULL COMMENT '审核意见',
    `effective_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否生效入网',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_audit_record_submission` (`submission_id`),
    KEY `idx_wujin_audit_record_action` (`action`),
    KEY `idx_wujin_audit_record_effective` (`effective_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金关系审核记录';

CREATE TABLE IF NOT EXISTS `wujin_search_rule_config` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '规则编号',
    `rule_type` varchar(64) NOT NULL COMMENT '规则类型：GRANULARITY_LIMIT/INTENT_DICT/ENTITY_ALIAS/WEIGHT',
    `lane` varchar(32) DEFAULT NULL COMMENT '泳道',
    `industry_code` varchar(64) DEFAULT NULL COMMENT '行业编码',
    `rule_value` varchar(512) NOT NULL COMMENT '规则值',
    `weight` int DEFAULT NULL COMMENT '权重',
    `status` tinyint NOT NULL COMMENT '开启状态',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_rule_type_lane` (`rule_type`, `lane`),
    KEY `idx_wujin_rule_industry` (`industry_code`),
    KEY `idx_wujin_rule_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金搜索规则配置';

CREATE TABLE IF NOT EXISTS `wujin_search_behavior_log` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '搜索行为编号',
    `user_id` bigint DEFAULT NULL COMMENT '用户编号',
    `keyword` varchar(128) NOT NULL COMMENT '关键词',
    `intent` varchar(64) DEFAULT NULL COMMENT '搜索意图',
    `result_lane` varchar(32) NOT NULL COMMENT '结果泳道',
    `industry_code` varchar(64) DEFAULT NULL COMMENT '行业编码',
    `chain_viewed` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否查看制造链',
    `classification_correct` bit(1) DEFAULT NULL COMMENT '分类是否正确',
    `high_risk_warning_triggered` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否触发高风险提示',
    `satisfaction_score` int DEFAULT NULL COMMENT '满意度评分',
    `response_time_millis` bigint NOT NULL COMMENT '响应时间毫秒',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_search_log_keyword` (`keyword`),
    KEY `idx_wujin_search_log_lane` (`result_lane`),
    KEY `idx_wujin_search_log_risk` (`high_risk_warning_triggered`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金搜索行为日志';

CREATE TABLE IF NOT EXISTS `wujin_sourcing_lead` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '寻源线索编号',
    `user_id` bigint DEFAULT NULL COMMENT '用户编号',
    `keyword` varchar(128) NOT NULL COMMENT '关键词',
    `lane` varchar(32) NOT NULL COMMENT '当前泳道：PRODUCT/PROCESS/MATERIAL',
    `source_keyword` varchar(128) DEFAULT NULL COMMENT '来源关键词',
    `industry` varchar(64) DEFAULT NULL COMMENT '行业上下文',
    `supplier_id` bigint DEFAULT NULL COMMENT '候选供应商编号',
    `supplier_name` varchar(128) DEFAULT NULL COMMENT '候选供应商名称',
    `merchant_id` bigint DEFAULT NULL COMMENT '分发商家编号',
    `contact_name` varchar(64) DEFAULT NULL COMMENT '联系人',
    `contact_phone` varchar(32) NOT NULL COMMENT '联系方式',
    `requirement` varchar(512) NOT NULL COMMENT '需求说明',
    `lead_status` varchar(32) NOT NULL COMMENT '线索状态：SUBMITTED/ASSIGNED/CONTACTED/QUOTED/CONVERTED/LOST',
    `dispatch_status` varchar(32) NOT NULL COMMENT '分发状态：PENDING/DISPATCHED',
    `dispatch_remark` varchar(512) DEFAULT NULL COMMENT '分发备注',
    `handle_remark` varchar(512) DEFAULT NULL COMMENT '商家处理备注',
    `dispatch_time` datetime DEFAULT NULL COMMENT '分发时间',
    `first_contact_time` datetime DEFAULT NULL COMMENT '首次联系时间',
    `quoted_time` datetime DEFAULT NULL COMMENT '报价时间',
    `converted_time` datetime DEFAULT NULL COMMENT '转化时间',
    `lost_time` datetime DEFAULT NULL COMMENT '流失时间',
    `process_duration_minutes` bigint DEFAULT NULL COMMENT '处理耗时分钟',
    `follow_stage` varchar(32) DEFAULT NULL COMMENT '商家跟进阶段',
    `next_follow_time` datetime DEFAULT NULL COMMENT '下次跟进时间',
    `quoted_amount` int DEFAULT NULL COMMENT '报价金额，单位：分',
    `win_probability` int DEFAULT NULL COMMENT '预计转化概率 0-100',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_sourcing_lead_keyword` (`keyword`),
    KEY `idx_wujin_sourcing_lead_lane` (`lane`),
    KEY `idx_wujin_sourcing_lead_merchant` (`merchant_id`),
    KEY `idx_wujin_sourcing_lead_status` (`lead_status`, `dispatch_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金一键寻源线索';

CREATE TABLE IF NOT EXISTS `wujin_monitor_snapshot` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '快照编号',
    `metric` varchar(64) NOT NULL COMMENT '指标',
    `metric_value` int NOT NULL COMMENT '指标值',
    `threshold_value` int DEFAULT NULL COMMENT '阈值',
    `audit_action` varchar(64) DEFAULT NULL COMMENT '审核动作',
    `alert_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否告警',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_monitor_snapshot_metric` (`metric`),
    KEY `idx_wujin_monitor_snapshot_alert` (`alert_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金监控指标快照';

CREATE TABLE IF NOT EXISTS `wujin_attribute_dictionary` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '属性编号',
    `code` varchar(64) NOT NULL COMMENT '属性编码',
    `name` varchar(64) NOT NULL COMMENT '属性名称',
    `group_name` varchar(64) NOT NULL COMMENT '属性分组',
    `lane` varchar(32) DEFAULT NULL COMMENT '适用泳道：PRODUCT/PROCESS/MATERIAL，为空表示三泳道通用',
    `category_id` bigint DEFAULT NULL COMMENT '适用五金分类编号',
    `value_type` varchar(32) NOT NULL COMMENT '值类型：TEXT/NUMBER/ENUM/MULTI_ENUM/BOOLEAN',
    `value_options` varchar(1024) DEFAULT NULL COMMENT '可选值 JSON 数组',
    `unit` varchar(32) DEFAULT NULL COMMENT '单位',
    `required_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必填',
    `searchable_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否参与搜索筛选',
    `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '状态：0=启用 1=停用',
    `remark` varchar(512) DEFAULT NULL COMMENT '备注',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_attribute_dictionary_code` (`code`),
    KEY `idx_wujin_attribute_dictionary_lane` (`lane`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金平台属性字典';

CREATE TABLE IF NOT EXISTS `wujin_product_attribute_value` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '属性值编号',
    `submission_id` bigint NOT NULL COMMENT '商家关系申报编号',
    `merchant_id` bigint NOT NULL COMMENT '商家编号',
    `product_id` bigint NOT NULL COMMENT '商品编号',
    `attribute_id` bigint DEFAULT NULL COMMENT '平台属性字典编号，非字典属性为空',
    `attribute_code` varchar(64) DEFAULT NULL COMMENT '属性编码',
    `attribute_name` varchar(64) NOT NULL COMMENT '属性名称',
    `attribute_value` varchar(255) NOT NULL COMMENT '属性值',
    `standard_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否平台标准属性',
    `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_product_attribute_value_submission` (`submission_id`),
    KEY `idx_wujin_product_attribute_value_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金商品标准属性值';

CREATE TABLE IF NOT EXISTS `wujin_product_custom_tag` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '标签编号',
    `submission_id` bigint DEFAULT NULL COMMENT '商家关系申报编号',
    `merchant_id` bigint NOT NULL COMMENT '商家编号',
    `product_id` bigint NOT NULL COMMENT '商品编号',
    `product_name` varchar(128) DEFAULT NULL COMMENT '商品名称',
    `tag_name` varchar(32) NOT NULL COMMENT '标签名称',
    `review_note` varchar(512) DEFAULT NULL COMMENT '商家审核说明',
    `audit_status` tinyint NOT NULL COMMENT '审核状态：10=待审核 30=审核通过 40=驳回',
    `audit_comment` varchar(512) DEFAULT NULL COMMENT '平台审核意见',
    `auditor_id` bigint DEFAULT NULL COMMENT '审核人编号',
    `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
    `creator` varchar(64) DEFAULT '' COMMENT '创建者',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` varchar(64) DEFAULT '' COMMENT '更新者',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_wujin_product_custom_tag_product` (`product_id`, `tag_name`),
    KEY `idx_wujin_product_custom_tag_status` (`audit_status`),
    KEY `idx_wujin_product_custom_tag_merchant` (`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='五金商品自定义标签';
