-- 社区互助养老模块建表语句

CREATE TABLE IF NOT EXISTS `aged_community` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `name`          varchar(64)  NOT NULL COMMENT '社区名称',
    `code`          varchar(32)  DEFAULT NULL COMMENT '社区编码',
    `area_code`     varchar(32)  DEFAULT NULL COMMENT '行政区划编码',
    `longitude`     decimal(12,8) DEFAULT NULL,
    `latitude`      decimal(12,8) DEFAULT NULL,
    `enabled`       bit(1)       DEFAULT b'1',
    `default_flag`  bit(1)       DEFAULT b'0',
    `remark`        varchar(255) DEFAULT NULL,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社区主体';

CREATE TABLE IF NOT EXISTS `aged_announcement` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `title`         varchar(128) NOT NULL,
    `content`       text         NOT NULL,
    `community_id`  bigint       DEFAULT NULL,
    `publish_time`  datetime     DEFAULT NULL,
    `expire_time`   datetime     DEFAULT NULL,
    `published`     bit(1)       DEFAULT b'1',
    `sort`          int          DEFAULT 0,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_community` (`community_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社区公告';

CREATE TABLE IF NOT EXISTS `aged_service` (
    `id`                    bigint       NOT NULL AUTO_INCREMENT,
    `name`                  varchar(64)  NOT NULL,
    `description`           varchar(255) DEFAULT NULL,
    `price`                 bigint       NOT NULL COMMENT '价格(分)',
    `duration_minutes`      int          DEFAULT 60,
    `volunteer_share_rate`  int          DEFAULT 0,
    `community_id`          bigint       DEFAULT NULL,
    `cross_community_visible` bit(1)     DEFAULT b'1',
    `enabled`               bit(1)       DEFAULT b'1',
    `create_time`           datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`           datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`               varchar(64)  DEFAULT NULL,
    `updater`               varchar(64)  DEFAULT NULL,
    `deleted`               bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务目录';

CREATE TABLE IF NOT EXISTS `aged_coupon_card` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `service_id`    bigint       NOT NULL,
    `title`         varchar(64)  NOT NULL,
    `description`   varchar(255) DEFAULT NULL,
    `deduct_times`  int          NOT NULL,
    `price`         bigint       NOT NULL,
    `valid_days`    int          NOT NULL,
    `enabled`       bit(1)       DEFAULT b'1',
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_service` (`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠卡定义';

CREATE TABLE IF NOT EXISTS `aged_coupon_ownership` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `card_id`       bigint       NOT NULL,
    `user_id`       bigint       NOT NULL,
    `elder_user_id` bigint       NOT NULL,
    `remain_times`  int          NOT NULL,
    `expire_time`   datetime     NOT NULL,
    `active`        bit(1)       DEFAULT b'1',
    `bind_order_id` bigint       DEFAULT NULL,
    `community_id`  bigint       DEFAULT NULL,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_user` (`user_id`),
    KEY `idx_elder` (`elder_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠卡资产';

CREATE TABLE IF NOT EXISTS `aged_elder_profile` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `user_id`       bigint       NOT NULL,
    `name`          varchar(32)  NOT NULL,
    `gender`        tinyint      DEFAULT NULL,
    `birthday`      date         DEFAULT NULL,
    `mobile`        varchar(20)  DEFAULT NULL,
    `address`       varchar(255) DEFAULT NULL,
    `latitude`      decimal(12,8) DEFAULT NULL,
    `longitude`     decimal(12,8) DEFAULT NULL,
    `community_id`  bigint       DEFAULT NULL,
    `health_notes`  varchar(255) DEFAULT NULL,
    `sos_subscribed` bit(1)      DEFAULT b'0',
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='长者档案';

CREATE TABLE IF NOT EXISTS `aged_family_link` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `elder_user_id` bigint       NOT NULL,
    `family_user_id` bigint      NOT NULL,
    `relation`      varchar(32)  DEFAULT NULL,
    `verify_mobile` varchar(20)  DEFAULT NULL,
    `verify_time`   datetime     DEFAULT NULL,
    `active`        bit(1)       DEFAULT b'1',
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_pair` (`elder_user_id`,`family_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='亲属绑定';

CREATE TABLE IF NOT EXISTS `aged_volunteer_profile` (
    `id`                bigint       NOT NULL AUTO_INCREMENT,
    `user_id`           bigint       NOT NULL,
    `name`              varchar(32)  NOT NULL,
    `gender`            tinyint      DEFAULT NULL,
    `avatar`            varchar(255) DEFAULT NULL,
    `mobile`            varchar(20)  DEFAULT NULL,
    `id_card_no`        varchar(32)  DEFAULT NULL,
    `skills`            varchar(255) DEFAULT NULL,
    `qualification_urls` varchar(512) DEFAULT NULL,
    `certification_status` int       DEFAULT 0,
    `certification_remark` varchar(255) DEFAULT NULL,
    `cross_community_enabled` bit(1) DEFAULT b'1',
    `default_community_id` bigint    DEFAULT NULL,
    `balance`           bigint       DEFAULT 0,
    `frozen_amount`     bigint       DEFAULT 0,
    `create_time`       datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`       datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`           varchar(64)  DEFAULT NULL,
    `updater`           varchar(64)  DEFAULT NULL,
    `deleted`           bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_volunteer_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='志愿者档案';

CREATE TABLE IF NOT EXISTS `aged_order` (
    `id`                bigint       NOT NULL AUTO_INCREMENT,
    `order_no`          varchar(32)  NOT NULL,
    `service_id`        bigint       NOT NULL,
    `service_name`      varchar(64)  DEFAULT NULL,
    `community_id`      bigint       DEFAULT NULL,
    `elder_user_id`     bigint       NOT NULL,
    `elder_profile_id`  bigint       DEFAULT NULL,
    `submitter_user_id` bigint       NOT NULL,
    `family_user_id`    bigint       DEFAULT NULL,
    `volunteer_user_id` bigint       DEFAULT NULL,
    `status`            int          NOT NULL,
    `payment_status`    int          NOT NULL,
    `amount`            bigint       NOT NULL,
    `payable_amount`    bigint       NOT NULL,
    `paid_amount`       bigint       DEFAULT 0,
    `volunteer_share_rate` int       DEFAULT 0,
    `volunteer_reward_amount` bigint DEFAULT 0,
    `coupon_ownership_id` bigint     DEFAULT NULL,
    `coupon_used`       bit(1)       DEFAULT b'0',
    `schedule_time`     datetime     NOT NULL,
    `duration_minutes`  int          DEFAULT 60,
    `address`           varchar(255) DEFAULT NULL,
    `latitude`          decimal(12,8) DEFAULT NULL,
    `longitude`         decimal(12,8) DEFAULT NULL,
    `contact_name`      varchar(32)  DEFAULT NULL,
    `contact_mobile`    varchar(20)  DEFAULT NULL,
    `prefer_gender`     varchar(16)  DEFAULT NULL,
    `prefer_age_range`  varchar(32)  DEFAULT NULL,
    `prefer_service_window` varchar(32) DEFAULT NULL,
    `note`              varchar(255) DEFAULT NULL,
    `service_summary`   varchar(255) DEFAULT NULL,
    `service_code`      varchar(8)   DEFAULT NULL,
    `service_code_expire_time` datetime DEFAULT NULL,
    `accept_time`       datetime     DEFAULT NULL,
    `check_in_time`     datetime     DEFAULT NULL,
    `check_in_longitude` decimal(12,8) DEFAULT NULL,
    `check_in_latitude` decimal(12,8) DEFAULT NULL,
    `check_in_address`  varchar(255) DEFAULT NULL,
    `onsite_time`       datetime     DEFAULT NULL,
    `complete_time`     datetime     DEFAULT NULL,
    `cancel_time`       datetime     DEFAULT NULL,
    `cancel_reason`     varchar(255) DEFAULT NULL,
    `evaluation_score`  int          DEFAULT NULL,
    `evaluation_content` varchar(255) DEFAULT NULL,
    `evaluation_public` bit(1)       DEFAULT b'0',
    `create_time`       datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`       datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`           varchar(64)  DEFAULT NULL,
    `updater`           varchar(64)  DEFAULT NULL,
    `deleted`           bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_elder` (`elder_user_id`),
    KEY `idx_volunteer` (`volunteer_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='养老服务订单';

CREATE TABLE IF NOT EXISTS `aged_order_event` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `order_id`      bigint       NOT NULL,
    `event_type`    varchar(32)  NOT NULL,
    `detail`        varchar(255) DEFAULT NULL,
    `operator_user_id` bigint    DEFAULT NULL,
    `operator_role` varchar(32)  DEFAULT NULL,
    `event_time`    datetime     DEFAULT CURRENT_TIMESTAMP,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单事件';

CREATE TABLE IF NOT EXISTS `aged_order_evidence` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `order_id`      bigint       NOT NULL,
    `evidence_type` varchar(16)  NOT NULL,
    `url`           varchar(255) NOT NULL,
    `duration`      int          DEFAULT NULL,
    `remark`        varchar(255) DEFAULT NULL,
    `uploader_user_id` bigint    DEFAULT NULL,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_order` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单佐证';

CREATE TABLE IF NOT EXISTS `aged_sos_record` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `elder_user_id` bigint       NOT NULL,
    `elder_profile_id` bigint    DEFAULT NULL,
    `trigger_user_id` bigint     DEFAULT NULL,
    `community_id`  bigint       DEFAULT NULL,
    `latitude`      decimal(12,8) DEFAULT NULL,
    `longitude`     decimal(12,8) DEFAULT NULL,
    `address`       varchar(255) DEFAULT NULL,
    `message`       varchar(255) DEFAULT NULL,
    `status`        int          DEFAULT 0,
    `handle_user_id` bigint      DEFAULT NULL,
    `handle_time`   datetime     DEFAULT NULL,
    `handle_result` varchar(255) DEFAULT NULL,
    `notify_snapshot` text       DEFAULT NULL,
    `related_order_id` bigint    DEFAULT NULL,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_elder` (`elder_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='SOS 记录';

CREATE TABLE IF NOT EXISTS `aged_withdraw_request` (
    `id`            bigint       NOT NULL AUTO_INCREMENT,
    `volunteer_user_id` bigint   NOT NULL,
    `amount`        bigint       NOT NULL,
    `status`        int          DEFAULT 0,
    `transfer_order_no` varchar(64) DEFAULT NULL,
    `review_user_id` bigint      DEFAULT NULL,
    `review_time`   datetime     DEFAULT NULL,
    `reject_reason` varchar(255) DEFAULT NULL,
    `remark`        varchar(255) DEFAULT NULL,
    `create_time`   datetime     DEFAULT CURRENT_TIMESTAMP,
    `update_time`   datetime     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `creator`       varchar(64)  DEFAULT NULL,
    `updater`       varchar(64)  DEFAULT NULL,
    `deleted`       bit(1)       DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_volunteer` (`volunteer_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='志愿者提现';
